//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAXI_PEZ.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int Id_Venta { get; set; }
        public Nullable<int> Id_Produtco { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
        public Nullable<int> Id_Promociones { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Facha { get; set; }
        public Nullable<int> Id_TipoPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual PROMOCIONES PROMOCIONES { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
    }
}
